[2023-09-04 23:01:55,105] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 23:01:55] "POST /marca HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 23:01:58,371] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 23:01:58] "GET /marca HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 23:02:14,574] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 23:02:14] "[35m[1mDELETE /marca HTTP/1.1[0m" 204 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 23:02:17,425] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 23:02:17] "GET /marca HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 23:02:34,104] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 23:02:34] "POST /modelo HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 23:02:40,841] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 23:02:40] "GET /modelo_id?codigo=4 HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 23:03:02,802] WARNING del_marca() L169  Erro ao excluir a marca de veiculo                  codigo #'6', A marca de veículo não foi encontrado na base - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\app.py L169 
[2023-09-04 23:03:02,803] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 23:03:02] "[33mDELETE /marca HTTP/1.1[0m" 404 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 23:03:05,923] WARNING del_marca() L154  Erro ao buscar a marca de veículo , Não é possível excluir! A Marca está associado há algum modelo. - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\app.py L154 
[2023-09-04 23:03:05,924] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 23:03:05] "[31m[1mDELETE /marca HTTP/1.1[0m" 400 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 23:03:29,250] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 23:03:29] "GET /modelos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 23:03:35,129] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 23:03:35] "GET /modelo_id?codigo=4 HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 23:03:41,786] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 23:03:41] "GET /marca_modelo_id?codigo_marca=5 HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 23:04:00,591] WARNING add_veiculo() L547  Erro ao adicionar o veiculo com a placa ABC-1234 e modelo 5, O modelo informado não existe no cadastro de modelos! - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\app.py L547 
[2023-09-04 23:04:00,592] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 23:04:00] "[33mPOST /veiculo HTTP/1.1[0m" 404 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 23:04:09,703] WARNING add_veiculo() L547  Erro ao adicionar o veiculo com a placa ABC-1333 e modelo 5, O modelo informado não existe no cadastro de modelos! - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\app.py L547 
[2023-09-04 23:04:09,704] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 23:04:09] "[33mPOST /veiculo HTTP/1.1[0m" 404 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 23:04:17,912] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 23:04:17] "GET /veiculos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 23:04:29,733] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 23:04:29] "GET /veiculos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 23:04:51,789] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 23:04:51] "GET /modelos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 23:05:03,392] WARNING add_veiculo() L547  Erro ao adicionar o veiculo com a placa ABC-1333 e modelo 4, O modelo informado não existe no cadastro de modelos! - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\app.py L547 
[2023-09-04 23:05:03,393] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 23:05:03] "[33mPOST /veiculo HTTP/1.1[0m" 404 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 23:06:19,231] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.15.138:5000 (Press CTRL+C to quit) - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 23:06:22,642] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 23:06:22] "POST /veiculo HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 23:06:27,586] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 23:06:27] "GET /veiculos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 23:12:38,124] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.15.138:5000 (Press CTRL+C to quit) - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 23:12:51,573] ERROR log_exception() L1449 Exception on /modelo_id [GET] - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask\app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask\app.py", line 1539, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask\app.py", line 1714, in make_response
    rv = jsonify(rv)
         ^^^^^^^^^^^
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask\json\__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask\json\__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\edumi\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\edumi\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\edumi\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask\json\__init__.py", line 51, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\edumi\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Marca is not JSON serializable
[2023-09-04 23:12:51,582] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 23:12:51] "[35m[1mGET /modelo_id?codigo=4 HTTP/1.1[0m" 500 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 23:15:44,852] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.15.138:5000 (Press CTRL+C to quit) - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 23:15:48,123] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 23:15:48] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 23:15:48,228] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 23:15:48] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 23:15:48,237] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 23:15:48] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
